### ISSUE TITLE
relative import for tests module does not work

### ISSUE THREAD

**Issue by SuhaanSyed** [SuhaanSyed/Battleship#24]

**Comment by SuhaanSyed** [comment]
Had to comment out import tests in main.py as it was breaking the whole game flow

```
Traceback (most recent call last):
  File "/Users/suhaansyed/Desktop/Suhaan/Projects/Battleship/run_game.py", line 2, in <module>
    from battleship_game.src.main import main
  File "/Users/suhaansyed/Desktop/Suhaan/Projects/Battleship/battleship_game/src/main.py", line 18, in <module>
    import tests
ModuleNotFoundError: No module named 'tests'
```

Error occurs when run_game.py is run

**Comment by ealmloff** [comment]
Fixed by https://github.com/SuhaanSyed/Battleship/commit/6428f9be2f604ef9c92c40d96036cb2839c58dec
